### PR TITLE
Test with Python 3.6 on Travis

### PR DESCRIPTION
**Pull request by ajdavis**
Attempt to leapfrog over a setuptools issue encountered when building
the docs with Python 3.4 on Travis

### CODE REVIEW

**Comment by ShaneHarvey** [comment]
Looks like it's also past time to drop support for python 2.6 :):
```
https://files.pythonhosted.org/packages/19/77/da358f5729ff046ceaf6c6a86755f9d8285719f93df6da15bb2440367d7e/pymongo-3.8.0.tar.gz (649kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9BJSld/pymongo/setup.py", line 9, in <module>
        raise RuntimeError("Python version >= 2.7 required.")
    RuntimeError: Python version >= 2.7 required.
```

**Comment by ajdavis** [comment]
Indeed! Trying 2.6 -> 2.7 now.

**Comment by ajdavis** [comment]
Miraculous, all checks passed. Shane, permission to merge?

**Comment by ShaneHarvey** [comment]
How do the py36 toxenv (eg `TOXENV=py36-docs`) settings work even thought they are not defined in tox.ini?

**Comment by ajdavis** [comment]
Whoops, this appears to be an easy mistake to make with Tox. I had defined a special command for py34-docs in tox.ini (the special command runs "sphinx-build"), so that's what Tox runs if TOXENV=py34-docs.

However, if TOXENV=py36-docs, then Tox a) accepts that this is a valid environment name, based on some inference it makes based on the existence of py34-docs?, and b) since there's no special command defined for py36-docs, it falls back to the default testenv, which just runs "setup.py test". I'll send another PR.

**Comment by ajdavis** [comment]
https://github.com/ajdavis/mongo-mockup-db/pull/31

**Pull request merged**
